AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "prd"

Resources:
  HouseMemeber:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "house-members-${Environment}"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  ListOfDay:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "list-of-day-${Environment}"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Type"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Type"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  ThisWeekCharge:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "this-week-charge-${Environment}"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  HouseMovein:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "house-move-in-${Environment}"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  HouseMoveout:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "house-move-out-${Environment}"
      AttributeDefinitions:
        - AttributeName: "House"
          AttributeType: "S"
        - AttributeName: "Room"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "House"
          KeyType: "HASH"
        - AttributeName: "Room"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
