AWSTemplateFormatVersion: 2010-09-09

Resources:
  BorderlessHouseMemeber:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'borderless-common-fee'
      AttributeDefinitions:
        - AttributeName: 'House'
          AttributeType: 'S'
        - AttributeName: 'Room'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'House'
          KeyType: 'HASH'
        - AttributeName: 'Room'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  TypesOfGarbage:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'borderless-type-of-garbage'
      AttributeDefinitions:
        - AttributeName: 'House'
          AttributeType: 'S'
        - AttributeName: 'GarbageType'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'House'
          KeyType: 'HASH'
        - AttributeName: 'GarbageType'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  PeopleInCharge:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'borderles-people-in-charge'
      AttributeDefinitions:
        - AttributeName: 'House'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'House'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  LineGroupId:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'borderles-line-groupid'
      AttributeDefinitions:
        - AttributeName: 'House'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'House'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  BorderlessMovein:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'borderless-house-move-in'
      AttributeDefinitions:
        - AttributeName: 'House'
          AttributeType: 'S'
        - AttributeName: 'Room'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'House'
          KeyType: 'HASH'
        - AttributeName: 'Room'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'

  BorderlessMoveout:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'borderless-house-move-out'
      AttributeDefinitions:
        - AttributeName: 'House'
          AttributeType: 'S'
        - AttributeName: 'Room'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'House'
          KeyType: 'HASH'
        - AttributeName: 'Room'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
