service: line-bot-borderless

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
  stage: api
  region: ap-northeast-1

functions:
  line_bot_response:
    handler: handler.line_bot_response
    events:
      #UTCでかくこと
      - schedule: cron(00 13 ? * MON *)
      - schedule: cron(00 13 ? * TUE *)
      - schedule: cron(00 13 ? * THU *)